# site settings
title: OSS Project
subtitle: by Team1
email: email@gmail.com
description: This project is ralated to Algorithm<br /> We add more algorithms<br /> <a href="https://github.com/19-2-SKKU-OSS/2019-2-OSS-L1">Our Github</a>
baseurl: "/2019-2-OSS-L1" # the subpath of your site, e.g. /blog
url: "https://19-2-skku-oss.github.io"# the base hostname & protocol for your site
author:
street_address: Sungkyunkwam Univ.
city: Suwon
country: Republic of Korea
phone: (031) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
